steps:
- name: 'gcr.io/cloud-builders/git'
  id: Clone repository
  args: ['clone', 'https://github.com/ONSdigital/blaise-gcp-publish-bucket-metadata.git']

- name: 'gcr.io/cloud-builders/gcloud'
  id: Checkout branch
  entrypoint: /bin/sh
  args: 
  - '-c'
  - |
    cd blaise-gcp-publish-bucket-metadata && \
    git checkout LU-5110

- name: 'gcr.io/cloud-builders/gcloud'
  id: Create function
  args:
  - functions
  - deploy
  - pubFileMetaData 
  - --source=. 
  - --region=europe-west2 
  - --runtime=python37 
  - --trigger-bucket=$PROJECT_ID-results
  - --set-env-vars=ON-PREM-SUBFOLDER=BL5,PROJECT_ID=$PROJECT_ID,TOPIC_NAME=$PROJECT_ID-export-topic
